from aw import SeaOfStarsAW
from cases.qqmusic_common import QqMusicCase


class PerformanceDynamic_qqm_0010(QqMusicCase):
    """Excel 7.0.2：QQ音乐播放、收藏及榜单浏览。"""

    @SeaOfStarsAW.function_log
    def run_case(self):
        for iteration in range(self.TEST_TIME):
            self.prepare_iteration()
            with self.capture_trace_5s(iteration, 1):
                self.step(1, '启动QQ音乐')
                self.start_qqmusic()
            self.step(2, '点击我的')
            self.open_mine()
            self.step(3, '点击最近')
            self.open_recent()
            self.step(4, '最近页面，上滑2次，下滑2次')
            self.browse_music(2, 2)
            self.step(5, '返回我的页')
            self.back()
            self.step(6, '点击本地')
            self.open_local()
            self.step(7, '返回我的页')
            self.back()
            self.step(8, '点击首页')
            self.tap('首页', min_y=780, wait=4)
            self.step(9, '点击搜索框')
            self.open_search_box()
            self.step(10, '输入红旗飘飘并搜索')
            self.search('红旗飘飘')
            self.step(11, '点击歌手')
            self.switch_result_tab('歌手')
            self.step(12, '点击综合')
            self.switch_result_tab('综合')
            self.step(13, '综合页面，上滑2次，下滑2次')
            self.browse_music(2, 2)
            self.step(14, '点击搜索后的第一个结果进行播放20s')
            self.play_first_search_result('红旗飘飘', seconds=20)
            self.step(15, '点击查看播放详情')
            self.ensure_player_detail()
            self.step(16, '点击暂停播放')
            self.pause_player()
            self.step(17, '点击收藏后取消收藏')
            self.favorite_then_unfavorite()
            self.step(18, '切换到歌词界面后返回到播放界面')
            self.lyrics_round_trip()
            self.step(19, '返回到首页')
            self.return_music_home()
            self.step(20, '点击排行榜')
            self.open_rankings()
            self.step(21, '排行榜页面，上滑2次，下滑2次')
            self.browse_music(2, 2)
            self.step(22, '点击热歌榜')
            self.open_chart('热歌榜')
            self.step(23, '返回排行榜')
            self.back()
            self.step(24, '切换到新歌榜')
            self.open_chart('新歌榜')
            self.step(25, '点击分享')
            self.tap('分享', max_y=140, wait=4)
            self.step(26, '点击音乐卡片')
            self.tap('音乐卡片', min_y=600, wait=6)
            if self.find('分享音乐卡片', max_y=140) is None:
                self.fail('未进入音乐卡片分享页')
            self.step(27, '返回QQ音乐主界面')
            self.return_music_home()
            with self.capture_trace_5s(iteration, 28):
                self.step(28, '滑动返回Home页')
                self.launcher()
