from aw import SeaOfStarsAW
from cases.douyin_common import DouyinCase


class PerformanceDynamic_douyin_0050(DouyinCase):
    """Excel 7.0.2：拍照预览，并与 Test 账号发送文字和媒体消息。"""

    @SeaOfStarsAW.function_log
    def run_case(self):
        for iteration in range(self.TEST_TIME):
            self.prepare_iteration()
            with self.capture_trace_5s(iteration, 1):
                self.step(1, '启动抖音')
                self.start_app(wait=5)
            self.normalize_home_after_launch()
            self.step(2, '点击+号')
            self.open_creation()
            self.step(3, '点击相册')
            self.open_creation_album()
            self.step(4, '返回+号页')
            self.close_creation_album()
            self.step(5, '点击照片')
            self.select_creation_photo_mode()
            self.step(6, '点击拍照')
            self.take_creation_photo()
            self.step(7, '点击选择音乐')
            self.open_photo_music()
            self.step(8, '选择音乐向上滑动6次')
            self.swipe_up_times(6)
            self.step(9, '返回照片编辑页面')
            self.close_photo_music()
            self.step(10, '点击下一步')
            self.next_from_photo_editor()
            self.step(11, '点击预览')
            self.preview_post()
            self.step(12, '返回抖音首页')
            self.discard_creation_and_return_home()
            self.step(13, '点击消息页面')
            self.open_messages()
            self.step(14, '进入测试账号(Test)聊天界面，向下滑动3次浏览')
            self.open_test_chat()
            self.swipe_down_times(3)
            self.step(15, '发送文字华为手机')
            self.send_chat_text('华为手机')
            self.step(16, '发送一个动态表情包')
            self.send_dynamic_emoji()
            self.step(17, '点击+')
            self.open_chat_more()
            self.step(18, '点击拍摄')
            self.enter_chat_camera()
            self.step(19, '拍摄图片')
            self.capture_chat_photo()
            self.step(20, '点击发送')
            self.send_chat_media()
            self.step(21, '点击拍摄')
            self.enter_chat_camera()
            self.step(22, '拍摄视频')
            self.capture_chat_video()
            self.step(23, '点击发送')
            self.send_chat_media()
            self.step(24, '点击+')
            self.open_chat_more()
            self.step(25, '点击相册')
            self.enter_chat_album()
            self.step(26, '相册页面上滑3次，下滑3次')
            self.browse(3, 3)
            self.step(27, '点击第一张图片')
            self.select_first_album_photo()
            self.step(28, '点击发送')
            self.send_chat_media()
            self.step(29, '返回抖音首页')
            self.return_main()
            self.step(30, '点击分享，选择测试账号')
            self.select_test_in_share_panel()
            self.step(31, '点击发送')
            self.send_selected_share()
            self.step(32, '返回抖音主界面')
            self.return_main()
            with self.capture_trace_5s(iteration, 33):
                self.step(33, '滑动返回Home页')
                self.launcher()
