from aw import SeaOfStarsAW
from cases.jingdong_common import JingdongCase


class PerformanceDynamic_jingdong_0030(JingdongCase):
    """搜索商品、评价、店铺、客服及秒送药店。"""

    @SeaOfStarsAW.function_log
    def run_case(self):
        for iteration in range(self.TEST_TIME):
            self.prepare_iteration()
            with self.capture_trace_5s(iteration, 1):
                self.step(1, '启动京东')
                self.start_jingdong()
            self.step(2, '点击搜索框')
            self.open_search()
            self.step(3, '搜索华为手机')
            self.submit_search('华为手机')
            self.step(4, '搜索结果页浏览，上滑5次，下滑5次')
            self.browse(5, 5)
            self.step(5, '点击顶部销量')
            self.tap('销量', max_y=520, fallback=(202, 454), wait=4)
            self.step(6, '点击第一个商品进入详情页')
            self.open_first_search_result()
            self.step(7, '浏览详情页，上滑5次，下滑5次')
            self.browse(5, 5)
            self.step(8, '点击商品图片')
            self.tap('图集', '商品图片1', contains=True,
                     fallback=(200, 245), wait=4)
            self.step(9, '图片左滑3次，右滑3次')
            for _ in range(3):
                self.device.swipe(0.8, 0.5, 0.2, 0.5, 0.3)
            for _ in range(3):
                self.device.swipe(0.2, 0.5, 0.8, 0.5, 0.3)
            self.step(10, '返回商品详情界面')
            self.edge_back()
            self.step(11, '上滑至评价')
            self.device.swipe(0.5, 0.75, 0.5, 0.32, 0.3)
            self.step(12, '点击评价')
            self.open_reviews_section()
            self.step(13, '点击全部评价')
            self.open_all_reviews()
            self.step(14, '浏览全部评价，上滑3次，下滑3次')
            self.browse(3, 3)
            self.step(15, '点击左下角店铺')
            self.tap('店铺', min_y=700, wait=5)
            self.step(16, '浏览店铺，上滑3次，下滑3次')
            self.browse(3, 3)
            self.step(17, '返回商品详情界面')
            self.edge_back()
            self.step(18, '点击客服')
            self.tap('客服', min_y=650, wait=5)
            self.step(19, '返回商品详情界面')
            self.edge_back()
            self.step(20, '点击立即购买')
            self.open_purchase()
            self.step(21, '点击确认')
            self.confirm_purchase()
            self.step(22, '返回京东主界面')
            self.return_home()
            self.step(23, '点击秒送')
            self.open_seconds()
            self.step(24, '点击外卖')
            self.open_takeout()
            self.step(25, '点击搜索框')
            self.device.click(190, 116)
            self.step(26, '输入药店')
            self.enter_text('药店', clear=True)
            self.step(27, '点击搜索')
            self.tap('搜索', max_y=180, fallback=(362, 116), wait=5)
            self.step(28, '浏览搜索结果，上滑3次，下滑3次')
            self.browse(3, 3)
            self.step(29, '点击第一个药店')
            self.open_first_merchant()
            self.step(30, '浏览药店，上滑3次，下滑3次')
            self.browse(3, 3)
            self.step(31, '返回京东主界面')
            self.return_home()
            with self.capture_trace_5s(iteration, 32):
                self.step(32, '滑动返回Home页')
                self.launcher()
